import { readFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import { strict as assert } from "node:assert";

const root = new URL("..", import.meta.url).pathname;
const index = readFileSync(join(root, "www", "index.html"), "utf8");
const manifest = JSON.parse(readFileSync(join(root, "package.json"), "utf8"));

assert(index.includes("#bevy"), "index.html should mount the Bevy canvas");
assert(index.includes("frame_input"), "index.html should forward camera/static frames to wasm");
assert(index.includes("./out/bevy_jepa.js"), "index.html should load wasm-bindgen output");
assert(index.includes("https://aberration.technology/model/burn_jepa"), "wasm page should reference remote burn_jepa model package root by default");
assert(index.includes("https://aberration.technology/model/burn_anyup"), "wasm page should reference remote burn_anyup model package root by default");
assert(index.includes("https://aberration.technology/model/burn_jepa_reconstruction"), "wasm page should reference remote burn_jepa_reconstruction model package root by default");
assert(index.includes("vjepa2_1_ttt"), "wasm page should default to the TTT V-JEPA 2.1 model profile");
assert(index.includes("vjepa2_1_base"), "wasm page should support the base V-JEPA 2.1 model profile");
assert(index.includes("model-manifest"), "wasm page should support explicit model manifest override");
assert(index.includes("anyup-model-manifest"), "wasm page should support explicit AnyUp manifest override");
assert(index.includes("reconstruction-model-manifest"), "wasm page should support explicit reconstruction manifest override");
assert(index.includes("model-base"), "wasm page should support localhost model base override");
assert(index.includes("model-profile"), "wasm page should support model profile query switching");
assert(index.includes("window.__burnJepaModelPackage"), "wasm page should pass sharded model bytes through a single package hook");
assert(index.includes("window.__burnAnyupModelPackage"), "wasm page should pass sharded AnyUp bytes through a package hook");
assert(index.includes("window.__burnJepaReconstructionModelPackage"), "wasm page should pass sharded reconstruction bytes through a package hook");
assert(index.includes("anyup_model_package_input"), "wasm page should preload AnyUp bpk parts into wasm");
assert(index.includes("reconstruction_model_package_input"), "wasm page should preload reconstruction bpk parts into wasm");
assert(index.includes('params.get("load-model")'), "wasm page should support load-model=false smoke mode");
assert(index.includes("bevy_jepa camera source running"), "index.html should expose camera runtime status");
assert(index.includes("bevy_jepa static source running"), "index.html should expose static runtime status");
assert(index.includes("getUserMedia"), "index.html should support browser camera capture");
assert(index.includes('params.get("camera-reader") === "processor"'), "camera processor capture should be opt-in");
assert(index.includes("camera processor failed; falling back to canvas capture"), "camera source should fall back to canvas capture when processor copy fails");
assert(index.includes("window.__jepaLastError"), "wasm page should publish detailed errors for console/debug access");
assert(index.includes("see console"), "wasm status errors should stay short and direct users to console diagnostics");
assert(!index.includes("runtime error: ${error"), "wasm page should not write long runtime errors into the status label");
assert(index.includes('queryNumber(["camera-width", "width"], 256'), "camera source should not request sub-256 frames by default");
assert(index.includes('queryNumber(["static-width", "width"], 256'), "static source should not generate sub-256 frames by default");
assert(index.includes('queryNumber(["static-width", "width"], 256, 3840, 512'), "static source should default to 512px frames");
assert(index.includes("usesStaticSource"), "index.html should support static-source smoke mode");
assert(index.includes("usesCameraSource"), "index.html should make camera-source selection explicit");
assert(index.includes("unsupported wasm frame source"), "index.html should reject unsupported source values");
assert(!index.includes("usesSyntheticSource"), "wasm page should not silently select generated frames");
assert(manifest.scripts["build:wasm"].includes("--out-name bevy_jepa"));
assert(existsSync(join(root, "src", "lib.rs")), "viewer source exists");
assert(existsSync(join(root, "src", "platform.rs")), "viewer camera platform source exists");
